mod artwork;
pub mod audio;
pub mod cli;
pub mod client;
mod cover;
pub mod daemon;
pub mod engine;
pub mod library;
pub mod media_controls;
pub mod model;
pub mod platform;
mod queue_edit;
pub mod settings;
pub mod spectrum;
mod spectrum_view;
pub mod store;
pub mod theme;
mod tmux;
pub mod tui;
pub mod wire;
