mod artwork;
pub mod audio;
pub mod cast;
pub mod cli;
pub mod client;
mod cover;
pub mod covers;
pub mod daemon;
mod deletion;
pub mod engine;
pub mod import_config;
pub mod imports;
pub mod library;
pub mod llm;
pub mod media_controls;
pub mod metadata;
pub mod model;
pub mod platform;
mod queue_edit;
#[cfg(target_os = "macos")]
pub mod relay;
pub mod settings;
pub mod spectrum;
mod spectrum_view;
pub mod store;
pub mod streams;
mod subprocess;
pub mod theme;
mod tmux;
pub mod tui;
mod video;
pub mod wire;
pub mod youtube;
